name: Next.js Build Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        working-directory: noteworthy-site
        run: |
          if [ -f "${{ github.workspace }}/noteworthy-site/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/noteworthy-site/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: noteworthy-site/package-lock.json

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            noteworthy-site/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('noteworthy-site/**/package-lock.json', 'noteworthy-site/**/yarn.lock') }}-${{ hashFiles('noteworthy-site/**.[jt]s', 'noteworthy-site/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('noteworthy-site/**/package-lock.json', 'noteworthy-site/**/yarn.lock') }}-

      - name: Install dependencies
        working-directory: noteworthy-site
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build with Next.js
        working-directory: noteworthy-site
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
